auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Yiling Xu
url: http://yilingxu.github.io
feed: /atom.xml
author_info: <a href="http://yilingxu.github.io/">Yiling Xu</a>
